{{- if .Values.django.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ringlet.fullname" . }}-django-hpa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ringlet.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ringlet.fullname" . }}-django
  minReplicas: {{ .Values.django.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.django.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.django.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.django.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
---
{{- if .Values.celery.worker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ringlet.fullname" . }}-celery-hpa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ringlet.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ringlet.fullname" . }}-celery-worker
  minReplicas: {{ .Values.celery.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.celery.worker.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.celery.worker.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
