apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ringlet.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ringlet.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.secrets.secretKey | quote }}
  DB_USER: {{ .Values.postgresql.env.POSTGRES_USER | quote }}
  DB_PASSWORD: {{ .Values.django.secrets.dbPassword | quote }}
