apiVersion: v1
kind: Service
metadata:
  name: {{ include "ringlet.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ringlet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.django.service.type }}
  ports:
  - port: {{ .Values.django.service.port }}
    targetPort: {{ .Values.django.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "ringlet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
